/**
 * Permission-Keys aus der DB-Tabelle `berechtigungen` als TS-Union-Type.
 *
 * AUTO-GENERIERT von tools/gen-permission-types.mjs. Manuelle Edits werden
 * beim nächsten Build überschrieben. Stand der Generierung: 2026-06-25.
 *
 * Verwendung:
 *   const ok = useHasPermission('baustellen.delete');  // Typo → Compile-Error
 */

export type PermissionKey =
  | "baustellen.view"
  | "baustellen.create"
  | "baustellen.edit"
  | "baustellen.delete"
  | "baustellen.termine"
  | "baustellen.kosten"
  | "baustellen.dokumente.view"
  | "baustellen.dokumente.upload"
  | "baustellen.dokumente.delete"
  | "mitarbeiter.view"
  | "mitarbeiter.create"
  | "mitarbeiter.edit"
  | "mitarbeiter.delete"
  | "mitarbeiter.view_sensitive"
  | "mitarbeiter.edit_sensitive"
  | "mitarbeiter.einladung_senden"
  | "stunden.view_eigene"
  | "stunden.view_partie"
  | "stunden.view_alle"
  | "stunden.create_eigene"
  | "stunden.create_andere"
  | "stunden.edit_alle"
  | "stunden.freigeben_zm"
  | "stunden.freigeben_buero"
  | "stunden.bsb.bestaetigen"
  | "urlaub.genehmigen"
  | "stunden.bsb.versenden"
  | "berichte.view"
  | "berichte.create"
  | "berichte.edit_eigene"
  | "berichte.edit_alle"
  | "berichte.delete"
  | "evaluierungen.view"
  | "evaluierungen.create"
  | "evaluierungen.edit"
  | "evaluierungen.unterschreiben"
  | "arbeitsplanung.view"
  | "arbeitsplanung.edit"
  | "arbeitsplanung.partien_verwalten"
  | "tagesplanung.view"
  | "tagesplanung.edit"
  | "tagesplanung.freigeben"
  | "fahrzeuge.view"
  | "fahrzeuge.create"
  | "fahrzeuge.edit"
  | "fahrzeuge.delete"
  | "kalkulator.view"
  | "kalkulator.edit_k3"
  | "kalkulator.anfragen_verwalten"
  | "konten.view_eigene"
  | "konten.view_alle"
  | "konten.edit_alle"
  | "arbeitszeitkalender.view"
  | "arbeitszeitkalender.edit"
  | "angebote.view"
  | "angebote.create"
  | "angebote.edit"
  | "angebote.delete"
  | "meintag.view"
  | "dashboard.view"
  | "admin.view"
  | "admin.taetigkeiten_verwalten"
  | "admin.zulagen_verwalten"
  | "admin.unterweisungs_vorlagen"
  | "admin.lohnzettel_verwalten"
  | "system.admin_panel"
  | "system.manage_permissions"
  | "system.view_audit"
  // Phase 5c (2026-06-29)
  | "berichte.freigeben"
  | "berichte.archivieren"
  | "mitarbeiter.einladung_resend"
  | "baustellen.edit_partie"
  | "baustellen.edit_status"
  | "angebote.status_aendern";
